[build]
  publish = "./" # ou "dist" se você gerar uma pasta com build
  functions = "netlify/functions"
  node_bundler = "esbuild"

[functions]
  included_files = ["netlify/functions/**"]

[build.environment]
  SUPABASE_URL = "https://niqphubutahhnrliyikl.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pcXBodWJ1dGFoaG5ybGl5aWtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDQ1NjgsImV4cCI6MjA2NjI4MDU2OH0.p4Pg0sEjmL_othOhYbrjW56SQBQCIkXWKlkzlQGDpeg"
