[build]
  publish = "./" # ou "dist" se você gerar uma pasta com build
  functions = "netlify/functions"
  node_bundler = "esbuild"

[functions]
  # Inclui o arquivo de mensagens usado pelas funções
  included_files = ["netlify/functions/**", "controle-de-produto.json", "mensagens.json"]

